name: Check semantic PR titles

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  title-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title's semantic conformance
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
